---
title: "BATBC and BATASHOES Prices"
date: "2018/04/07"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(message = F,echo = F,comment = NA)
```
---

# Housekeeping stuff

--

## Loading library

```{r, echo=TRUE}
library(tidyverse)
library(tidyquant)
library(forecast)
```

--

## Loading data

```{r, echo=FALSE}
load("~/Dropbox/Docs/Research/stock_market/RDATA/batbc_bata_clean.RData")

batbc.bata.mo.ret <- batbc.bata.clean %>% 
    group_by(symbol) %>% 
    tq_transmute(select=price,
		 mutate_fun=periodReturn,
		 type="log",
		 period="monthly")

batbc.bata.mo.ret.med <- batbc.bata.mo.ret %>% 
    group_by(symbol,mo=month(date,label=TRUE)) %>% 
    summarize(med.ret=median(monthly.returns)) 

	 
```
---
class: inverse,center, middle
# BATBC: Month-wise median return

---

```{r }
batbc.bata.mo.ret.med %>% 
    filter(symbol=="BATBC") %>% 
    arrange(desc(med.ret))

```
---

class: inverse,center, middle
# BATASHOES: Month-wise median return

---

```{r }
batbc.bata.mo.ret.med %>% 
    filter(symbol=="BATASHOE") %>% 
    arrange(desc(med.ret))

```
---
class: center, middle, inverse
# Charting monthly  returns
---

```{r chartline, fig.width=14, fig.height=10  }
batbc.bata.mo.ret %>% 
    group_by(month(date)) %>% 
    ggplot(aes(month(date,label=T),monthly.returns))+
                   geom_boxplot()  +
		   facet_wrap(~symbol,ncol=1) +
  theme_tq()
		   
```

---

```{r, fig.width=14, fig.height=10 }
batbc.bata.mo.ret.med %>% 
    ggplot(aes(mo,med.ret)) +
      geom_bar(aes(fill=symbol), stat="identity",position="dodge") +
  theme_tq()
```


